spring.dataSource.url: jdbc:mysql://localhost:3306/devpostsdb?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
spring.dataSource.username: root
spring.dataSource.password: test123341
spring.jpa.hibernate.ddl-auto: update

#spring.jpa.show-sql: true
#spring.jpa.generate-ddl: false
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true

#spring.mvc.view.prefix: /src/main/resources/templates/
#spring.mvc.view.suffix: .html
#spring.messages.basename: validation