#Replace 'localhost' to ip if DB on other server
#Replace 'devpostsdb' with your DB name
spring.dataSource.url: jdbc:mysql://u2jdsvfuheag93qv:XZX2wxRhHl33YhbgJwAy@bsvjrvblkisuaomwadw9-mysql.services.clever-cloud.com:3306/bsvjrvblkisuaomwadw9?verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=Europe/Paris
#  :mysql://localhost:3306/devpostsdb?verifyServerCertificate=false&useSSL=false&requireSSL=false
#  &serverTimezone=Europe/Moscow}
server.port: ${PORT:8080}

##Replace with your DB username here:
#spring.dataSource.username: epiz_26906310
##Replace with your DB password here:
#spring.dataSource.password: mr1n78v6

spring.jpa.hibernate.ddl-auto: update

#Max size for uploads media
spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS: false

#Replace with your host here:
blog.host: mktarasov-java-skillbox.epizy.com:8080

#Replace with your email here:
moderator.email: developerspublics@gmail.com
#Replace with your application password here:
moderator.email.password: wzhaqlnptimbivpl

#path to avatars on server
uploads.home: /home/vol9_6/epizy.com/epiz_26906310/mktarasov-java-skillbox.epizy.com
#path to avatars on browser
avatar.path: avatar
#path to uploads img on posts
uploads.path: upload

#post announce size
announce.size: 1000

#avatar width
avatar.width: 36
#avatar height
avatar.height: 36

#uploads max width
uploads.width: 640

#captcha total chars
captcha.chars: 6
#captcha height
captcha.height: 35
#captcha width
captcha.width: 100
#Replace with your captcha life-time in milliseconds here:
captcha.life.time: 3600000