spring.dataSource.url: jdbc:mysql://localhost:3306/devpostsdb?verifyServerCertificate=false&useSSL=false&requireSSL=false
  &serverTimezone=UTC

#Replace with your DB username here:
spring.dataSource.username: root
#Replace with your DB password here:
spring.dataSource.password: test123341
spring.jpa.hibernate.ddl-auto: update

spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS: false

#Replace with your host here:
blog.host: localhost:8080

#Replace with your email here:
moderator.email: developerspublics@gmail.com
#Replace with your application password here:
moderator.email.password: wzhaqlnptimbivpl

#Replace with your captcha life-time here:
captcha.life.time: 3600000

#path to avatars
uploads.home: C:/home
uploads.path: upload

#spring.resources.static-locations: file:///upload

#post announce size
announce.size: 1000