#Replace with your DB host
db.host: bsvjrvblkisuaomwadw9-mysql.services.clever-cloud.com
#Replace with your DB name
db.name: bsvjrvblkisuaomwadw9
#Replace with your time-zone
db.timezone: Europe/Paris
##Replace with your DB username here:
spring.dataSource.username: u2jdsvfuheag93qv
##Replace with your DB password here:
spring.dataSource.password: XZX2wxRhHl33YhbgJwAy

spring.dataSource.url: jdbc:mysql://${db.host}:3306/${db.name}?reconnect=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=${db.timezone}

server.port: ${PORT:8080}
spring.jpa.hibernate.ddl-auto: update

#Max size for uploads media
spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS: false

#Replace with your web host here:
blog.host: mktarasov-java-skillbox.herokuapp.com

#Replace with your email here:
moderator.email: developerspublics@gmail.com
#Replace with your application password here:
moderator.email.password: wzhaqlnptimbivpl

#path to images on server
uploads.home: /tmp/codon/tmp/images/
#path to avatars on browser
avatar.path: avatar
#path to uploads img on posts
uploads.path: upload

#post announce size
announce.size: 1000

#avatar width
avatar.width: 36
#avatar height
avatar.height: 36
#uploads max width
uploads.width: 640

#captcha total chars
captcha.chars: 6
#captcha height
captcha.height: 35
#captcha width
captcha.width: 100
#Replace with your captcha life-time in milliseconds here:
captcha.life.time: 3600000