spring:
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://${ADDON_HOST}:${ADDON_PORT}/${ADDON_DB}?reconnect=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=${db.timezone}
    username: ${ADDON_USER}
    password: ${ADDON_PASSWORD}
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${PORT}

db:
  timezone: ${ADDON_TIMEZONE}

moderator:
  email: ${MODERATOR_EMAIL}
  password: ${MODERATOR_PASSWORD}

uploads:
  home: /tmp/codon/tmp/images
  path: upload
  width: 640

avatar:
  path: avatar
  width: 36
  height: 36

announce:
  size: 1000

tag:
  min:
    weight: 0.22

captcha:
  chars: 6
  height: 35
  width: 100
  life:
    time: 3600000

images:
  auto:
    clean:
      time: 864000000

blog:
  host: mktarasov-java-pg-skillbox.herokuapp.com
  title: Developers Publications
  subtitle: Рассказы разработчиков
  phone: +7 904 550-48-47
  email: mktarasov@gmail.com
  copyright: Михаил Тарасов
  copyrightFrom: 2020