#Replace 'bsvjrvblkisuaomwadw9-mysql.services.clever-cloud.com' to ip of DB
#Replace 'bsvjrvblkisuaomwadw9' with your DB name
spring.dataSource.url: jdbc:mysql://bsvjrvblkisuaomwadw9-mysql.services.clever-cloud.com:3306/bsvjrvblkisuaomwadw9?reconnect=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=Europe/Paris
#spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
server.port: ${PORT:8080}

##Replace with your DB username here:
spring.dataSource.username: u2jdsvfuheag93qv
##Replace with your DB password here:
spring.dataSource.password: XZX2wxRhHl33YhbgJwAy

spring.jpa.hibernate.ddl-auto: update

#Max size for uploads media
spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS: false

#Replace with your host here:
blog.host: mktarasov-java-skillbox.herokuapp.com

#Replace with your email here:
moderator.email: developerspublics@gmail.com
#Replace with your application password here:
moderator.email.password: wzhaqlnptimbivpl

#path to images on server
uploads.home: ${APP_HOME}/images/
#path to avatars on browser
avatar.path: avatar
#path to uploads img on posts
uploads.path: upload

#post announce size
announce.size: 1000

#avatar width
avatar.width: 36
#avatar height
avatar.height: 36
#uploads max width
uploads.width: 640

#captcha total chars
captcha.chars: 6
#captcha height
captcha.height: 35
#captcha width
captcha.width: 100
#Replace with your captcha life-time in milliseconds here:
captcha.life.time: 3600000